security:

  encoders:
    App\Entity\User:
      algorithm: sodium

  providers:
    security_users:
      entity: { class: App\Entity\User, property: email }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: true
      pattern: ^/
      user_checker: App\Security\UserChecker
      form_login:
        check_path: security_login
        login_path: security_login
        provider: security_users
      logout:
        path: security_logout
        target: security_login

  access_control:
    - { path: ^/dashboard, roles: ROLE_USER }
    - { path: ^/admin, roles: ROLE_ADMIN }
