version: "3"

networks:
  symfony_shop_local:
    external: true

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/services/app/Dockerfile
    networks:
      - symfony_shop_local
    volumes:
      - app_sources:/app
      - app_cache:/app/var/cache
  web:
    build:
      context: ..
      dockerfile: ./docker/services/web/Dockerfile
    depends_on:
      - app
    environment:
      - VIRTUAL_HOST=eshop.symfony.local
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
    networks:
      - symfony_shop_local
    volumes:
      - app_sources:/app
  database:
    build:
      context: ..
      dockerfile: ./docker/services/database/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=5ecr3t
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - symfony_shop_local
    volumes:
      - app_database:/var/lib/mysql
  node:
    build:
      context: ..
      dockerfile: ./docker/services/node/Dockerfile
    command: ["yarn", "run", "build"]
    depends_on:
      - app
    networks:
      - symfony_shop_local
    user: node
    volumes:
      - app_sources:/app

volumes:
  app_sources:
  app_cache:
  app_database:
