services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Admin\UserAdmin:
    arguments: [ ~, App\Entity\User, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Users, label: Users }
