services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true # Public for testing reason (we need to mock services and replaces them within Symfony container)
    bind:
      $mailerFromAddress: '%mailerFromAddress%'

  App\EventListener\Security\UserCreationEventListener:
    tags:
      - { name: kernel.event_listener, event: App\Event\Security\UserRegisteredEvent, method: onUserRegistered }
      - { name: kernel.event_listener, event: App\Event\Security\UserCreatedEvent, method: onUserCreated }
